name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.3

      - name: Build
        run: go build -ldflags='-s -w'

      - name: UPX Compress
        uses: crazy-max/ghaction-upx@v1
        with:
          version: latest
          files: |
            gitig
          args: -fq

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: gitig
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
